/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ReferenzenRouteImport } from './routes/referenzen'
import { Route as UeberMichRouteImport } from './routes/ueber-mich'
import { Route as VeranstaltungenRouteImport } from './routes/veranstaltungen'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ProjekteIndexRouteImport } from './routes/projekte/index'
import { Route as ProjekteBallonUltralaufRouteImport } from './routes/projekte/ballon-ultralauf'
import { Route as ProjekteHammerBackyardUltraRouteImport } from './routes/projekte/hammer-backyard-ultra'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenRoute = ReferenzenRouteImport.update({
  id: '/referenzen',
  path: '/referenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberMichRoute = UeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const VeranstaltungenRoute = VeranstaltungenRouteImport.update({
  id: '/veranstaltungen',
  path: '/veranstaltungen',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjekteIndexRoute = ProjekteIndexRouteImport.update({
  id: '/projekte/',
  path: '/projekte/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjekteBallonUltralaufRoute = ProjekteBallonUltralaufRouteImport.update({
  id: '/projekte/ballon-ultralauf',
  path: '/projekte/ballon-ultralauf',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjekteHammerBackyardUltraRoute =
  ProjekteHammerBackyardUltraRouteImport.update({
    id: '/projekte/hammer-backyard-ultra',
    path: '/projekte/hammer-backyard-ultra',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/mcp': typeof McpRoute
  '/referenzen': typeof ReferenzenRoute
  '/ueber-mich': typeof UeberMichRoute
  '/veranstaltungen': typeof VeranstaltungenRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/projekte/ballon-ultralauf': typeof ProjekteBallonUltralaufRoute
  '/projekte/hammer-backyard-ultra': typeof ProjekteHammerBackyardUltraRoute
  '/projekte/': typeof ProjekteIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/mcp': typeof McpRoute
  '/referenzen': typeof ReferenzenRoute
  '/ueber-mich': typeof UeberMichRoute
  '/veranstaltungen': typeof VeranstaltungenRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/projekte/ballon-ultralauf': typeof ProjekteBallonUltralaufRoute
  '/projekte/hammer-backyard-ultra': typeof ProjekteHammerBackyardUltraRoute
  '/projekte': typeof ProjekteIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/mcp': typeof McpRoute
  '/referenzen': typeof ReferenzenRoute
  '/ueber-mich': typeof UeberMichRoute
  '/veranstaltungen': typeof VeranstaltungenRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/projekte/ballon-ultralauf': typeof ProjekteBallonUltralaufRoute
  '/projekte/hammer-backyard-ultra': typeof ProjekteHammerBackyardUltraRoute
  '/projekte/': typeof ProjekteIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/mcp'
    | '/referenzen'
    | '/ueber-mich'
    | '/veranstaltungen'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/projekte/ballon-ultralauf'
    | '/projekte/hammer-backyard-ultra'
    | '/projekte/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/mcp'
    | '/referenzen'
    | '/ueber-mich'
    | '/veranstaltungen'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/projekte/ballon-ultralauf'
    | '/projekte/hammer-backyard-ultra'
    | '/projekte'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/mcp'
    | '/referenzen'
    | '/ueber-mich'
    | '/veranstaltungen'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/projekte/ballon-ultralauf'
    | '/projekte/hammer-backyard-ultra'
    | '/projekte/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  McpRoute: typeof McpRoute
  ReferenzenRoute: typeof ReferenzenRoute
  UeberMichRoute: typeof UeberMichRoute
  VeranstaltungenRoute: typeof VeranstaltungenRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProjekteBallonUltralaufRoute: typeof ProjekteBallonUltralaufRoute
  ProjekteHammerBackyardUltraRoute: typeof ProjekteHammerBackyardUltraRoute
  ProjekteIndexRoute: typeof ProjekteIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen': {
      id: '/referenzen'
      path: '/referenzen'
      fullPath: '/referenzen'
      preLoaderRoute: typeof ReferenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-mich': {
      id: '/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/ueber-mich'
      preLoaderRoute: typeof UeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veranstaltungen': {
      id: '/veranstaltungen'
      path: '/veranstaltungen'
      fullPath: '/veranstaltungen'
      preLoaderRoute: typeof VeranstaltungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekte/': {
      id: '/projekte/'
      path: '/projekte'
      fullPath: '/projekte/'
      preLoaderRoute: typeof ProjekteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekte/ballon-ultralauf': {
      id: '/projekte/ballon-ultralauf'
      path: '/projekte/ballon-ultralauf'
      fullPath: '/projekte/ballon-ultralauf'
      preLoaderRoute: typeof ProjekteBallonUltralaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekte/hammer-backyard-ultra': {
      id: '/projekte/hammer-backyard-ultra'
      path: '/projekte/hammer-backyard-ultra'
      fullPath: '/projekte/hammer-backyard-ultra'
      preLoaderRoute: typeof ProjekteHammerBackyardUltraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  McpRoute: McpRoute,
  ReferenzenRoute: ReferenzenRoute,
  UeberMichRoute: UeberMichRoute,
  VeranstaltungenRoute: VeranstaltungenRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProjekteBallonUltralaufRoute: ProjekteBallonUltralaufRoute,
  ProjekteHammerBackyardUltraRoute: ProjekteHammerBackyardUltraRoute,
  ProjekteIndexRoute: ProjekteIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
